# Generated by Django 2.2.5 on 2020-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200708_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='mp', max_length=200),
            preserve_default=False,
        ),
    ]
