# Generated by Django 2.2.5 on 2020-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('M', 'Model'), ('S', 'Sport'), ('A', 'Art')], max_length=200),
        ),
    ]
