# Generated by Django 2.2.5 on 2022-10-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200917_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Model', 'M'), ('Sport', 'S'), ('Art', 'A')], max_length=200),
        ),
    ]
