# Generated by Django 2.2.5 on 2022-10-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221015_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Model', 'M'), ('Sport', 'S'), ('Art', 'A'), ('Tech', 'IT'), ('Travel', 'T')], max_length=200),
        ),
    ]
