# Generated by Django 2.2.5 on 2022-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221015_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Model', 'Model'), ('Sport', 'Sport'), ('Art', 'Art'), ('Tech', 'Tech'), ('Travel', 'Travel')], max_length=200),
        ),
    ]
